server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/shopdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest