services:
  postgres-filestoring:
    image: postgres:15-alpine
    container_name: postgres-filestoring
    environment:
      POSTGRES_DB: ${FILESTORING_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5440:5433"
    volumes:
      - filestoring_pg_data:/var/lib/postgresql/data

  postgres-fileanalysis:
    image: postgres:15-alpine
    container_name: postgres-fileanalysis
    environment:
      POSTGRES_DB: ${FILEANALYSIS_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5433"
    volumes:
      - fileanalysis_pg_data:/var/lib/postgresql/data

  file-storing-service:
    build: ./file-storing-service
    container_name: file-storing-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-filestoring:5432/${FILESTORING_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      FILE_STORAGE_PATH: ${FILE_STORAGE_PATH}
    depends_on:
      - postgres-filestoring
    ports:
      - "8081:8081"
    volumes:
      - file_storage:/app/uploads

  file-analysis-service:
    build: ./file-analysis-service
    container_name: file-analysis-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-fileanalysis:5432/${FILEANALYSIS_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      FILE_STORING_URL: ${FILE_STORING_URL}
    depends_on:
      - postgres-fileanalysis
      - file-storing-service
    ports:
      - "8082:8082"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - file-storing-service
      - file-analysis-service
    ports:
      - "8080:8080"

volumes:
  filestoring_pg_data:
  fileanalysis_pg_data:
  file_storage:

